# Generated by Django 4.2.2 on 2023-07-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_team_invite_team_alter_inquiry_email_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.team'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
