# Generated by Django 4.2.2 on 2023-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_team_alter_taskstatus_status_delete_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
