# Generated by Django 4.2.2 on 2023-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0002_problem_status_problem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_status',
            name='status',
            field=models.CharField(choices=[('PEN', 'PENDING'), ('SUB', 'SUBMITTED'), ('VER', 'VERIFIED')], default='PEN', max_length=3),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
