# Generated by Django 4.2.2 on 2023-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("EXP", "Expert"),
                    ("BEG", "Beginner"),
                    ("GOO", "Good"),
                    ("AVG", "Average"),
                ],
                default="BEG",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="techstack",
            field=models.TextField(default=None, null=True, verbose_name="Techstack"),
        ),
    ]
