# Generated by Django 4.2.2 on 2023-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_proficiency_user_techstack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="techstack",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Techstack"
            ),
        ),
    ]
