# Generated by Django 4.2.2 on 2023-06-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_member_acceptance_status_alter_member_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("user", "team")},
        ),
    ]
