# Generated by Django 4.2.2 on 2023-06-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.program'),
        ),
    ]
