# Generated by Django 4.2.2 on 2023-07-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('dsa', 'DSA'), ('web', 'Web'), ('app', 'App'), ('ui', 'UI/UX')], max_length=3)),
                ('topic', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
