# Generated by Django 4.2.2 on 2023-07-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_team_invite_team_alter_inquiry_email_and_more'),
        ('learning_resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='domain',
        ),
        migrations.AddField(
            model_name='resource',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.program'),
            preserve_default=False,
        ),
    ]
